// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuickBite.Domain.Enums;
using QuickBite.Infrastructure.Persistence;

#nullable disable

namespace QuickBite.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuickBiteDbContext))]
    [Migration("20260920000001_SeedDemoData")]
    partial class SeedDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_pedido", new[] { "pendiente", "confirmado", "preparando", "listo", "en_camino", "entregado", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_repartidor", new[] { "disponible", "ocupado", "inactivo" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "metodo_pago", new[] { "efectivo", "tarjeta" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rol_usuario", new[] { "cliente", "administrador", "repartidor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_notificacion", new[] { "pedido_nuevo", "cambio_estado", "asignacion", "sistema", "recordatorio" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuickBite.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("boolean")
                        .HasColumnName("es_predeterminada");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitud");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Referencia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("referencia");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_direcciones");

                    b.HasIndex("Ciudad")
                        .HasDatabaseName("idx_direcciones_ciudad");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uq_direccion_predeterminada_por_usuario")
                        .HasFilter("es_predeterminada = TRUE");

                    b.ToTable("direcciones", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.AuditAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Detalles")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria_acciones");

                    b.HasIndex("CreadoEn")
                        .IsDescending()
                        .HasDatabaseName("idx_auditoria_fecha");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_auditoria_usuario");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("idx_auditoria_entidad");

                    b.ToTable("auditoria_acciones", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<DateTime>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_carritos");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_carritos_estado");

                    b.HasIndex("ExpiraEn")
                        .HasDatabaseName("idx_carritos_expiracion")
                        .HasFilter("estado = 'activo'");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uq_carritos_usuario_id");

                    b.ToTable("carritos", null, t =>
                        {
                            t.HasCheckConstraint("CK_carritos_estado", "estado IN ('activo','abandonado','convertido')");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AgregadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agregado_en");

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("CarritoId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrito_id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_carrito_items");

                    b.HasIndex("CarritoId")
                        .HasDatabaseName("ix_carrito_items_carrito_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_carrito_items_producto_id");

                    b.ToTable("carrito_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_carrito_items_cantidad", "cantidad > 0");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.CartItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarritoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrito_item_id");

                    b.Property<Guid>("OpcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("opcion_id");

                    b.HasKey("Id")
                        .HasName("pk_carrito_item_opciones");

                    b.HasIndex("CarritoItemId")
                        .HasDatabaseName("ix_carrito_item_opciones_carrito_item_id");

                    b.HasIndex("OpcionId")
                        .HasDatabaseName("ix_carrito_item_opciones_opcion_id");

                    b.ToTable("carrito_item_opciones", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_categorias_nombre");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.DeliveryPerson", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("EntregasCompletadas")
                        .HasColumnType("integer")
                        .HasColumnName("entregas_completadas");

                    b.Property<DeliveryPersonStatus>("EstadoDisponibilidad")
                        .HasColumnType("estado_repartidor")
                        .HasColumnName("estado_disponibilidad");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Vehiculo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehiculo");

                    b.HasKey("UsuarioId")
                        .HasName("pk_repartidores");

                    b.HasIndex("EntregasCompletadas")
                        .IsDescending()
                        .HasDatabaseName("idx_repartidores_entregas");

                    b.HasIndex("EstadoDisponibilidad")
                        .HasDatabaseName("idx_repartidores_estado");

                    b.ToTable("repartidores", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid?>("ActualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("actualizado_por");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("ProductoId")
                        .HasName("pk_inventario");

                    b.HasIndex("ActualizadoPor")
                        .HasDatabaseName("ix_inventario_actualizado_por");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("idx_inventario_stock_bajo")
                        .HasFilter("stock <= stock_minimo");

                    b.ToTable("inventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventario_stock", "stock >= 0");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean")
                        .HasColumnName("leido");

                    b.Property<DateTime?>("LeidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leido_en");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensaje");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<NotificationType>("Tipo")
                        .HasColumnType("tipo_notificacion")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_notificaciones_pedido_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_notificaciones_usuario_id");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime?>("CanceladoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_en");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("ConfirmadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmado_en");

                    b.Property<decimal>("CostoEnvio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_envio");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("DireccionEntregaSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion_entrega_snapshot");

                    b.Property<Guid?>("DireccionId")
                        .HasColumnType("uuid")
                        .HasColumnName("direccion_id");

                    b.Property<DateTime?>("EnCaminoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("en_camino_en");

                    b.Property<DateTime?>("EntregadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregado_en");

                    b.Property<OrderStatus>("Estado")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("ListoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("listo_en");

                    b.Property<PaymentMethodType>("MetodoPago")
                        .HasColumnType("metodo_pago")
                        .HasColumnName("metodo_pago");

                    b.Property<Guid?>("MetodoPagoId")
                        .HasColumnType("uuid")
                        .HasColumnName("metodo_pago_id");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_pedido");

                    b.Property<DateTime?>("PreparandoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preparando_en");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("repartidor_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_pedidos_cliente");

                    b.HasIndex("CreadoEn")
                        .IsDescending()
                        .HasDatabaseName("idx_pedidos_creado");

                    b.HasIndex("DireccionId")
                        .HasDatabaseName("ix_pedidos_direccion_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_pedidos_estado");

                    b.HasIndex("MetodoPagoId")
                        .HasDatabaseName("ix_pedidos_metodo_pago_id");

                    b.HasIndex("NumeroPedido")
                        .IsUnique()
                        .HasDatabaseName("uq_pedidos_numero");

                    b.HasIndex("RepartidorId")
                        .HasDatabaseName("idx_pedidos_repartidor");

                    b.HasIndex("Estado", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_pedidos_estado_fecha");

                    b.ToTable("pedidos", null, t =>
                        {
                            t.HasCheckConstraint("CK_pedidos_costo_envio", "costo_envio >= 0");

                            t.HasCheckConstraint("CK_pedidos_subtotal", "subtotal >= 0");

                            t.HasCheckConstraint("CK_pedidos_total", "total >= 0");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_producto");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_pedido_items");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("idx_pedido_items_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("idx_pedido_items_producto");

                    b.HasIndex("PedidoId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("uq_pedido_items_producto")
                        .HasFilter("producto_id IS NOT NULL");

                    b.ToTable("pedido_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_pedido_items_cantidad", "cantidad > 0");

                            t.HasCheckConstraint("CK_pedido_items_precio", "precio_unitario >= 0");

                            t.HasCheckConstraint("CK_pedido_items_subtotal", "subtotal >= 0");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.OrderItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NombreOpcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_opcion");

                    b.Property<Guid>("PedidoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_item_id");

                    b.Property<decimal>("PrecioAdicional")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_adicional");

                    b.HasKey("Id")
                        .HasName("pk_pedido_item_opciones");

                    b.HasIndex("PedidoItemId")
                        .HasDatabaseName("ix_pedido_item_opciones_pedido_item_id");

                    b.ToTable("pedido_item_opciones", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<OrderStatus?>("EstadoAnterior")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_anterior");

                    b.Property<OrderStatus>("EstadoNuevo")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_nuevo");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pedido_historial_estados");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedido_historial_estados_pedido_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_pedido_historial_estados_usuario_id");

                    b.ToTable("pedido_historial_estados", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean")
                        .HasColumnName("usado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens_recuperacion_password");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_tokens_recuperacion_password_usuario_id");

                    b.ToTable("tokens_recuperacion_password", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_metodos_pago");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_metodos_pago_nombre");

                    b.ToTable("metodos_pago", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("idx_productos_categoria_id");

                    b.HasIndex("Disponible")
                        .HasDatabaseName("idx_productos_disponible")
                        .HasFilter("disponible = TRUE");

                    b.HasIndex("Precio")
                        .HasDatabaseName("idx_productos_precio");

                    b.ToTable("productos", null, t =>
                        {
                            t.HasCheckConstraint("CK_productos_precio", "precio >= 0");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioAdicional")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_adicional");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_producto_opciones");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_producto_opciones_producto_id");

                    b.ToTable("producto_opciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_producto_opciones_precio", "precio_adicional >= 0");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.ProductPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo");

                    b.Property<decimal>("PrecioAnterior")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_anterior");

                    b.Property<decimal>("PrecioNuevo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_nuevo");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_producto_precios_historicos");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_producto_precios_historicos_producto_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_producto_precios_historicos_usuario_id");

                    b.ToTable("producto_precios_historicos", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origen");

                    b.Property<bool>("Revocado")
                        .HasColumnType("boolean")
                        .HasColumnName("revocado");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens_refresco");

                    b.HasIndex("ExpiraEn")
                        .HasDatabaseName("idx_tokens_refresco_expiracion")
                        .HasFilter("revocado = FALSE");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_tokens_refresco_usuario_id");

                    b.ToTable("tokens_refresco", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean")
                        .HasColumnName("editable");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_configuracion_sistema");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("uq_configuracion_sistema_clave");

                    b.ToTable("configuracion_sistema", (string)null);
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<short>("IntentosFallidos")
                        .HasColumnType("smallint")
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Rol")
                        .HasColumnType("rol_usuario")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_usuarios_activo")
                        .HasFilter("activo = TRUE");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_email");

                    b.HasIndex("Rol")
                        .HasDatabaseName("idx_usuarios_rol");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_usuarios_email", "email ~* '^[^@]+@[^@]+\\.[^@]+$'");
                        });
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Address", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direcciones_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.AuditAction", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditoria_acciones_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Cart", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithOne("Carrito")
                        .HasForeignKey("QuickBite.Domain.Entities.Cart", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carritos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.Cart", "Carrito")
                        .WithMany("Items")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_items_carritos_carrito_id");

                    b.HasOne("QuickBite.Domain.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_items_productos_producto_id");

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.CartItemOption", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.CartItem", "CarritoItem")
                        .WithMany("Opciones")
                        .HasForeignKey("CarritoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_item_opciones_carrito_items_carrito_item_id");

                    b.HasOne("QuickBite.Domain.Entities.ProductOption", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_item_opciones_productos_opciones_opcion_id");

                    b.Navigation("CarritoItem");

                    b.Navigation("Opcion");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.DeliveryPerson", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithOne("Repartidor")
                        .HasForeignKey("QuickBite.Domain.Entities.DeliveryPerson", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repartidores_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "ActualizadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ActualizadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventario_usuarios_actualizado_por");

                    b.HasOne("QuickBite.Domain.Entities.Product", "Producto")
                        .WithOne("Inventario")
                        .HasForeignKey("QuickBite.Domain.Entities.Inventory", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_productos_producto_id");

                    b.Navigation("ActualizadoPorUsuario");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Notification", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.Order", "Pedido")
                        .WithMany("Notificaciones")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notificaciones_pedidos_pedido_id");

                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificaciones_usuarios_usuario_id");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Order", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuarios_cliente_id");

                    b.HasOne("QuickBite.Domain.Entities.Address", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedidos_direcciones_direccion_id");

                    b.HasOne("QuickBite.Domain.Entities.PaymentMethod", "MetodoPagoCatalogo")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_metodos_pago_metodo_pago_id");

                    b.HasOne("QuickBite.Domain.Entities.DeliveryPerson", "Repartidor")
                        .WithMany("Pedidos")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedidos_repartidores_repartidor_id");

                    b.Navigation("Cliente");

                    b.Navigation("Direccion");

                    b.Navigation("MetodoPagoCatalogo");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.Order", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_pedidos_pedido_id");

                    b.HasOne("QuickBite.Domain.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedido_items_productos_producto_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.OrderItemOption", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.OrderItem", "PedidoItem")
                        .WithMany("Opciones")
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_item_opciones_pedido_items_pedido_item_id");

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.Order", "Pedido")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_historial_estados_pedidos_pedido_id");

                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_pedido_historial_estados_usuarios_usuario_id");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithMany("TokensRecuperacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_recuperacion_password_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Product", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.Category", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.ProductOption", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.Product", "Producto")
                        .WithMany("Opciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_producto_opciones_productos_producto_id");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.ProductPriceHistory", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.Product", "Producto")
                        .WithMany("PreciosHistoricos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_producto_precios_historicos_productos_producto_id");

                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_producto_precios_historicos_usuarios_usuario_id");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("QuickBite.Domain.Entities.User", "Usuario")
                        .WithMany("TokensRefresco")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_refresco_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.CartItem", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Category", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.DeliveryPerson", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Order", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("Items");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.Product", b =>
                {
                    b.Navigation("Inventario");

                    b.Navigation("Opciones");

                    b.Navigation("PreciosHistoricos");
                });

            modelBuilder.Entity("QuickBite.Domain.Entities.User", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Carrito");

                    b.Navigation("Direcciones");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Repartidor");

                    b.Navigation("TokensRecuperacion");

                    b.Navigation("TokensRefresco");
                });
#pragma warning restore 612, 618
        }
    }
}
