using FluentValidation;
using QuickBite.Application.Catalog.Dtos;
namespace QuickBite.Application.Catalog.Validators;
public sealed class CreateCategoryValidator : AbstractValidator<CreateCategoryRequest> { public CreateCategoryValidator() { RuleFor(x => x.Nombre).NotEmpty().MaximumLength(100); RuleFor(x => x.Descripcion).MaximumLength(255); RuleFor(x => x.Icon).MaximumLength(32); } }
public sealed class UpdateCategoryValidator : AbstractValidator<UpdateCategoryRequest> { public UpdateCategoryValidator() { RuleFor(x => x.Nombre).MaximumLength(100).When(x => x.Nombre != null); RuleFor(x => x.Icon).MaximumLength(32); } }
public sealed class CreateProductValidator : AbstractValidator<CreateProductRequest> { public CreateProductValidator() { RuleFor(x => x.Nombre).NotEmpty().MaximumLength(150); RuleFor(x => x.Precio).GreaterThanOrEqualTo(0); RuleFor(x => x.ImagenUrl).MaximumLength(500); } }
public sealed class UpdateProductValidator : AbstractValidator<UpdateProductRequest> { public UpdateProductValidator() { RuleFor(x => x.Nombre).MaximumLength(150).When(x => x.Nombre != null); RuleFor(x => x.Precio).GreaterThanOrEqualTo(0).When(x => x.Precio != null); } }
public sealed class CreateOptionValidator : AbstractValidator<CreateProductOptionRequest> { public CreateOptionValidator() { RuleFor(x => x.Nombre).NotEmpty().MaximumLength(100); RuleFor(x => x.PrecioAdicional).GreaterThanOrEqualTo(0); } }
public sealed class ProductFilterValidator : AbstractValidator<ProductFilterRequest> { public ProductFilterValidator() { RuleFor(x => x.Page).GreaterThanOrEqualTo(1); RuleFor(x => x.Limit).InclusiveBetween(1, 50); RuleFor(x => x.PrecioMin).GreaterThanOrEqualTo(0).When(x => x.PrecioMin != null); RuleFor(x => x.PrecioMax).GreaterThanOrEqualTo(0).When(x => x.PrecioMax != null); RuleFor(x => x).Must(x => x.PrecioMin == null || x.PrecioMax == null || x.PrecioMin <= x.PrecioMax).WithMessage("precio_min no puede ser mayor que precio_max"); RuleFor(x => x.Orden).Must(o => o == null || new[] { "relevancia", "precio_asc", "precio_desc", "nombre_asc", "nombre_desc" }.Contains(o)).WithMessage("orden invalido"); } }
public sealed class AdjustStockValidator : AbstractValidator<AdjustStockRequest> { public AdjustStockValidator() { RuleFor(x => x.Stock).GreaterThanOrEqualTo(0); RuleFor(x => x.Motivo).MaximumLength(500); } }
